longhorn-volume-manager:
  volumes:
    - appName: procrastin
      volumeName: data
      volumeSize: 1

procrastin:
  defaultPodOptions:
    securityContext:
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    nodeSelector:
          kubernetes.io/hostname: "worker-1"

  controllers:
    api:
      replicas: 1
      containers:
        api:
          image:
            repository: ghcr.io/bbombardella/procrastin-api
            tag: latest
          env:
            PUID: 1000
            PGID: 1000
            TZ: Europe/Paris
            HOST: 0.0.0.0
            PORT: 3000
          envFrom:
            - secretRef:
                name: procrastin-secrets
          securityContext:
            runAsUser: 0
            runAsGroup: 0

  service:
    api:
      controller: api
      type: ClusterIP
      ports:
        http:
          port: 3000

  ingress:
    cloudflare-tunnel:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: cloudflare-tunnel
      hosts:
        - host: "procrastin-api.bartho.dev"
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: api
                port: http

  persistence:
    data:
      existingClaim: pvc-procrastin-procrastin-data
      globalMounts:
        - path: /app/data

